Feature/class effects
dmphillippo/multinma pull request #37
Opened 2024-04-17 13:50 UTC by sjperren

Adding class effects into the multinma package

2024-08-08 15:19 UTC, dmphillippo requested changes
Excellent work Sam, thank you! 🙂 

I have been through and suggested changes. Check that you are happy with these, come back to me if you disagree or think things are wrong. I think you should be able to review and merge these into your PR within GitHub. Also I reviewed these online, so please check that everything still works as expected afterwards!

There are a few other things we still need to do:

- [ ]  Add yourself as a contributor to the DESCRIPTION file
  ```r
  Authors@R: 
    c(person(given = c("David", "M."),
             family = "Phillippo",
             role = c("aut", "cre"),
             email = "david.phillippo@bristol.ac.uk",
             comment = c(ORCID = "0000-0003-2672-7841")),
      person(given = c("Samuel", "J."),
              family = "Perren",
              role = "ctb",
              email = "sam.perren@bristol.ac.uk",
              comment = c(ORCID = ...)))
  ```

  You might want to create an [ORCID](https://orcid.org) if you don't have one already, and a nice email "alias" for yourself [here](https://www.bris.ac.uk/it-services/applications/mailname/mailname.html)

- [ ] Add basic tests. 
  * Checking that the new arguments to `nma()` give the expected error messages
  * Running some basic made up class effects models with `test_grad = TRUE` (i.e. no samples) to check that the different options behave properly and the `class_mean` and `class_sd` parameters are named correctly in the output.
  * These can both go in `tests/testthat/test-nma.R`.

- [ ] Add the social anxiety data, and demonstrate with a vignette? This vignette can also have tests at the end, to make sure that we are getting the expected numerical results.

2024-08-19 12:09 UTC, sjperren reviewed
Those suggested changes seemed reasonable.

2024-09-18 14:18 UTC, sjperren reviewed
I'm trying to pull these changes into my repository so i can run it in R. Got a bit messy so if I submit this I'm hopefully I can pull it all cleanly and test it all.

2025-03-04 16:33 UTC, sjperren reviewed
Hi David,

Finally got the package checks and tests all coming back good now. 

Let me know if there is anything missing or could be done better.

BW

Sam

2025-03-07 11:53 UTC, dmphillippo requested changes
Thanks Sam! This is really great, only a last few things to look at.

2025-03-07 11:53 UTC, dmphillippo commented on R/data.R
> +#' that are further categorised into 17 distinct classes. The interventions of interest include oral drugs,
```suggestion
#' in adults . The 41 treatments are further categorised into 17 distinct classes. The interventions of interest include oral drugs,
```

2025-03-07 11:53 UTC, dmphillippo commented on R/data.R
> +#' Following Mayo-Wilson et al. \insertCite{mayo2014psychological}{multinma} the results are analysed as standardised mean differences (SMD) to allow comparisons.
```suggestion
#' Following Mayo-Wilson et al. \insertCite{mayo2014psychological}{multinma} the data are given as standardised mean differences (SMD) to allow comparison across the different scales used in each study.
```

2025-03-07 11:53 UTC, dmphillippo commented on R/nma.R
> +
```suggestion
```

2025-03-07 11:53 UTC, dmphillippo commented on R/nma.R
> +      stop("Some classes listed in 'class_sd' are not found in 'network$classes'")
```suggestion
      stop("Some classes listed in 'class_sd' are not present in the network.")
```

2025-03-07 11:53 UTC, dmphillippo commented on R/nma.R
> -    inform("Note: Network is disconnected. See ?is_network_connected for more details.")
These checks are necessary - can you add them back in?

2025-03-07 11:53 UTC, dmphillippo commented on git
Delete this file

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/model_common.stan
> +    // Priors for class mean parameters
```suggestion
  if (class_effects == 0) {
    prior_select_lp(d, prior_trt_dist, prior_trt_location, prior_trt_scale, prior_trt_df);
  } else {
    // Priors for class mean parameters
```

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/model_common.stan
> +      allbeta[(totns + t)] ~ std_normal();
```suggestion
      // Add dummy information to unused allbeta parameters to avoid Stan warnings
      allbeta[(totns + t)] ~ std_normal();
```

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/transformed_data_common.stan
> +
```suggestion

int<lower=0> n_class_trts = num_elements(which_gt0a(which_CE));  // Number of treatments with class effects
array[n_class_trts] which_class_trt = which_gt0a(which_CE); // Vector mapping classes to treatments
```

Rather than calling `which_gt0a(which_CE)` lots of times, defining a data variable to reuse

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/transformed_data_common.stan
> +int<lower=0> which_class_sd[class_effects ? n_class : 0]; // Vector to map class SDs to classes
```suggestion
array[class_effects ? nt-1 : 0] int<lower=0> which_class; // Vector to mapping treatments to class effects
array[class_effects ? n_class : 0] int<lower=0> which_class_sd; // Vector to map class SDs to classes
```

Avoid using deprecated array syntax

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/parameters_common.stan
> +vector[class_effects ? size(which_gt0a(which_CE)) : 0] z_class;
```suggestion
vector[class_effects ? n_class_trts : 0] z_class;
```

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/transformed_parameters_common.stan
> +    d[which_gt0a(which_CE)] = class_mean[which_CE[which_gt0a(which_CE)]] + filtered_class_sd .* z_class;
```suggestion
    f_class = class_mean[which_CE[which_class_trt]] - d[which_class_trt] + filtered_class_sd .* z_class;
    d[which_class_trt] = class_mean[which_CE[which_class_trt]] + filtered_class_sd .* z_class;
```

Can we also replace `filtered_class_sd` with `class_sd[which_CE_sd[which_class_trt]]`?

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/transformed_parameters_common.stan
> +  }
I think filtered_class_sd is unnecessary - see next comment

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/transformed_parameters_common.stan
> +  vector[class_effects ? max(which_class) : 0] filtered_class_sd; // class sds assigned to treatments (non zero values)
Unnecessary? See below?

2025-03-07 11:53 UTC, dmphillippo commented on inst/stan/include/transformed_parameters_common.stan
> +  tau[1] * RE_L * u_delta
```suggestion
  RE ? (
    RE_sparse ?
      tau[1] * csr_matrix_times_vector(n_delta, n_delta, RE_L_w, RE_L_v, RE_L_u, u_delta) :
      tau[1] * RE_L * u_delta
```

2025-03-07 11:53 UTC, dmphillippo commented on man/social_anxiety.Rd
This will need regenerating by running document()

2025-03-07 11:53 UTC, dmphillippo commented on tests/testthat/test-nma.R
> +              info = "All class_sd parameters should match the pattern class_sd[...]")
Can you check the actual names are correct, i.e. have the class names and sd group names? These tests aren't really checking anything at the moment, since lines 83:34 only pull out parameters that satisfy this test anyway.

2025-03-07 11:53 UTC, dmphillippo commented on tests/testthat/test-nma.R
> +                    prior_het = half_normal(5))
```suggestion
                    prior_het = half_normal(5),
                    test_grad = TRUE)
```

No need to actually run nma() here

2025-03-07 11:53 UTC, dmphillippo commented on tests/testthat/test-nma.R
> +sa_fit_EXclass_RE <- nma(sa_net, trt_effects = "random", prior_trt = normal(0, 100), prior_het = half_normal(5), class_effects = "exchangeable", prior_class_sd = normal(0.33,0.1), class_sd = list(`Ex
```suggestion
sa_fit_EXclass_RE <- nma(sa_net, trt_effects = "random", prior_trt = normal(0, 100), prior_het = half_normal(5), class_effects = "exchangeable", prior_class_sd = normal(0.33,0.1), class_sd = list(`Exercise and SH no support` = c("Exercise promotion", "Self-help no support"), `SSRIs and NSSA` = c("SSRI/SNRI", "NSSA"), `Psychodynamic & Other psychological therapies` = c("Psychodynamic psychotherapy", "Other psychological therapies")), test_grad = TRUE)
```

No need to actually run nma() here. Can you format this nicely over a few lines too?

2025-03-07 11:53 UTC, dmphillippo commented on vignettes/example_social_anxiety.Rmd
See comments on PDF

2025-03-07 11:53 UTC, dmphillippo commented on vignettes/example_social_anxiety.log
Delete this file

2025-03-07 11:53 UTC, dmphillippo commented on vignettes/vignette_overview.html
Can you add the social anxiety example to the vignette overview?

2025-03-18 10:12 UTC, dmphillippo commented on tests/testthat/test-nma.R
> +  expect_error(nma(sa_net, class_effect = "exchangeable", class_sd = list(group1 = c("Exposure", "NonExistentClass"))), "Some classes listed in 'class_sd' are not found in 'network$classes'", fixed =
```suggestion
  expect_error(nma(sa_net, class_effect = "exchangeable", class_sd = list(group1 = c("Exposure", "NonExistentClass"))), "Some classes listed in 'class_sd' are not present in the network", fixed = TRUE)
```

2025-03-20 14:06 UTC, dmphillippo reviewed
Looking good! I'll review a last few bits locally before merging.

2025-03-20 14:06 UTC, dmphillippo commented on vignettes/vignette_overview.Rmd
> +[Social anxiety](example_social_anxiety.html.html) | Continuous | Normal | Identity | Model selection with class models
```suggestion
[Social anxiety](example_social_anxiety.html.html) | Continuous | Normal | Identity | Model selection with class effects models
```

2025-03-21 12:24 UTC, dmphillippo commented
All looks great, I'll accept the PR now. Thank you!

2025-03-21 12:24 UTC, merged